language: generic
dist: trusty
os: linux
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-9
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - llvm-9
      - llvm-9-dev
      - clang-9
      - libllvm9
      - libc++-7-dev
      - libc++abi-7-dev
      - libgcc-4.9-dev
      - libobjc-4.9-dev
      - libclang-common-9-dev
      - libclang1-9
      - llvm-9-runtime
matrix:
  include:
    - os: osx
      env:
        - CXX=clang++ PATH=/usr/local/opt/llvm@9/bin:$PATH LLVM_DIR=/usr/local/opt/llvm@9 LDFLAGS:=-L/usr/local/opt/llvm@9/lib CPPFLAGS=-I/usr/local/opt/llvm@6/include
        - CONFIG_ARGS="-DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++"
      install: brew install llvm@9
      cache:
        directories: ~/Library/Caches/Homebrew/
    - os: osx
      env:
        - CXX=clang++ PATH=/usr/local/opt/llvm@9/bin:$PATH LLVM_DIR=/usr/local/opt/llvm@9 LDFLAGS:=-L/usr/local/opt/llvm@9/lib CPPFLAGS=-I/usr/local/opt/llvm@9/include
        - CONFIG_ARGS="-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++"
      install: brew install llvm@9
      cache:
        directories: ~/Library/Caches/Homebrew/
env:
  global:
    - CC=clang-9 CXX=clang++-9
    - PATH=$TRAVIS_BUILD_DIR/cmake-3.8.1-Linux-x86_64/bin:$PATH
    - LLVM_DIR=/usr/lib/llvm-9
  matrix:
    - CONFIG_ARGS="-DCMAKE_BUILD_TYPE:STRING=Debug"
    - CONFIG_ARGS=
install: curl https://cmake.org/files/v3.8/cmake-3.8.1-Linux-x86_64.tar.gz | tar xz
script: mkdir build && pushd build && cmake $CONFIG_ARGS $TRAVIS_BUILD_DIR && make -j4 && popd
