language: generic

matrix:
    include:
      - os: linux
        dist: bionic
        sudo: required
      - os: osx
        osx_image: xcode7.2


before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update       ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install cmake gcc g++; fi

script:
  - . ./build.sh
