language: generic
node_js:
  - "12.13"
matrix:
    include:
      - os: linux
        dist: bionic
        sudo: required
      - os: osx
        osx_image: xcode11.1
        sudo: required

env:
  - SVF_CTIR=1 SVF_Z3=1

before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update       ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test       ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update       ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install cmake gcc-9 g++-9 nodejs; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 900 --slave /usr/bin/g++ g++ /usr/bin/g++-9; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo ln -s /Applications/Xcode-11.1.app /Applications/Xcode.app ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo ln -s /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk ; fi

script:
  - git stash --all
  - echo $(pwd)
  - cd $TRAVIS_BUILD_DIR
  - npm_version=`npm v svf-tools version`
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sed  -i '/version/s/[^:]*$/'"\"${npm_version}\",/" package.json; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then git add .; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then git commit -m'update version'; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then npm version patch; fi
  - git clone "https://github.com/SVF-tools/Test-Suite.git"
  - . ./build.sh
  - cd ./Release-build
  - ctest
  - cd $TRAVIS_BUILD_DIR

after_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd ..; fi
  - git clone https://github.com/SVF-tools/SVF-npm.git
  - cp -rf $TRAVIS_BUILD_DIR/include ./SVF-npm/SVF-$TRAVIS_OS_NAME/
  - cp $TRAVIS_BUILD_DIR/Release-build/lib/libSvf.a ./SVF-npm/SVF-$TRAVIS_OS_NAME/Release-build/lib
  - cp $TRAVIS_BUILD_DIR/Release-build/lib/CUDD/libCudd.a ./SVF-npm/SVF-$TRAVIS_OS_NAME/Release-build/lib/CUDD
  - cd SVF-npm
  - git status
  - git add .
  - git commit -m'update svflib'
  - npm version patch
  - git push https://JasonZhongZexin:${git_key}@github.com/SVF-tools/SVF-npm.git   HEAD:master

deploy:
  provider: npm
  email: ${npm_email}
  api_key: ${npm_token} 
