codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: 62% # If auto, it will compare with the last commit. This could be set to an exact number such as 70% or higher.
        threshold: 0.01% # Allow the coverage to drop by 0.01%, and posting a success status.
        base: auto
    patch:
      default:
        target: auto
        threshold: 0.01%
        base: auto

coverage:
  precision: 2
  round: down
  range: "70...100"
  
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no 
